### ISSUE TITLE
DLC cards are not included in VanillaCardIDs

### ISSUE THREAD

**Issue by CodePointer** [KittenAqua/TrainworksModdingTools#143]
I'm working on the modding and I want to find the card "For The Greater Good". I think the rebel unit is a very interesting mechanism. However, I can't find the asset's name from Constants/VanillaCardIDs.cs. Also, some DLC cards such as "Apex Imp" are not included.

So where can I find the asset's name with the card name? Or, is there a way to find the assets' names via some modding tools given in the tutorial?

**Comment by brandonandzeus** [comment]
This is fixed as of 6bdb760574f807d3a7441b2579d06cdd8778379d

I will get the newly added Types and Traits in a separate commit.

**Comment by brandonandzeus** [comment]
I believe I got them all now.
