### ISSUE TITLE
Newer CardTraits and CardEffects missing from the API

### ISSUE THREAD

**Issue by RisingDusk** [KittenAqua/TrainworksModdingTools#92]
I noticed this particular issue earlier today while attempting to add CardTraitStrongerMagicPower (Attuned) to an existing card, only to find that CardTraitStrongerMagicPower was missing from the VanillaCardTraitTypes class. In talking to Chronometrics on Discord, he confirmed that it was an issue needing to be resolved.

**Comment by brandonandzeus** [comment]
This is now fixed. I've also added new Constant files for RoomModifiers and CardTriggerEffects.
